version: "3.9" 

services:
  quarkus:
    image: ${username}/${artifactId} 
    ports:
      - "8080:8080"
    links:
      - h2
  h2:
    build: 
      context: ./src/main/docker
      dockerfile: Dockerfile.h2
